Views
GeekyHacks/FlightOperationsBlog pull request #6
Opened 2024-01-23 19:36 UTC by GeekyHacks

In this PR I did the following:
- Added partials to use in the index and show files for the usersconroller
- Added Index & show methods in the usersController
- Added partials to use in the index and show files for the postsConroller
- Added Index & show methods in the postsController
- Added initial css styling to both user & post files

2024-01-23 19:55 UTC, prolajumokeoni commented
Hi @GeekyHacks, please fix the stylelint errors on your project, please this is a comment not a review 👍🏿

2024-01-23 20:08 UTC, prolajumokeoni commented
Hi @GeekyHacks 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that  has Stylelint errors please fix it 👍🏿 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2024-01-24 07:53 UTC, Ibizugbe requested changes
Hi @GeekyHacks 👋🏼👋🏼👋🏼,

![request change](https://github.com/GeekyHacks/FlightOperationsBlog/assets/64643995/55da3fe7-e4c5-49da-ab32-6e1038e09099)
 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Nice job making use of ruby partials👍🏼.
- [x] Liinters are passing👍🏼.
- [x] gitflow is used👍🏼


## Required Changes ♻️

- [ ] Kindly ensure to study the wireframe provided in the [requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md) and ensure the respective links to their respective pages are provided and their functionalities are implemented👍🏼.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-24 07:53 UTC, Ibizugbe commented on app/views/users/_listuser.html.erb
> +  </div>
Nice job so far👍🏼. You are meant to make this a link or add a link that leads the user to the user show page (each user rendered should link to their respective show page)😉. please do well to ensure your views match the wireframe as this is a requirement👍🏼.

yours
<img width="1354" alt="image" src="https://github.com/GeekyHacks/FlightOperationsBlog/assets/64643995/0c128337-c4ce-4772-8191-934804ca4a0d">

wireframe
<img width="1013" alt="image" src="https://github.com/GeekyHacks/FlightOperationsBlog/assets/64643995/99b93672-b10a-4413-8746-8b2715589d1a">


<img width="991" alt="image" src="https://github.com/GeekyHacks/FlightOperationsBlog/assets/64643995/ef45e26e-ca83-4682-9c05-cedac52c9238">



As regards the wireframe, this is the same for all your pages, try to ensure your views match the wireframes and the necessary links to the corresponding views are provided😉😉

2024-01-24 07:53 UTC, Ibizugbe commented on app/views/users/show.html.erb
> +<%= render partial: 'biouser', locals: { user: :id } %>
For your `user_show` page, kindly ensure a method is implemented to render the 3 most recent posts as shown in the [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_user_page.png) and also, do well to implement the `see all posts` link that takes you to the [`users_post` index page](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_user_all_posts.png) as shown in the respective wireframe😉. and also do well to ensure your views matches the wireframe👍🏼.

2024-01-24 07:53 UTC, Ibizugbe commented on app/views/posts/show.html.erb
> +<%= render partial: 'biopost', locals: { post: @post } %>
Nice job making use of ruby partials, as this makes your codebase maintainable 😉. Kindly ensure to stick to the [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_single_post.png) and ensure all comments for a post are rendered in the post show page👍🏼.

2024-01-24 23:03 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @GeekyHacks,

#### Nice job making the required changes. Unfortunately, you missed some of them but you are almost there.

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] As required by the previous reviewer, as per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md#:~:text=Project%20requirements-,Implement%20the%20design%20from%20the%20sneak%20peek%20wireframes,-.), The user info cards should take the whole width of the page in `users index`, `users show`, and `posts index` views. Please fix that.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://github.com/GeekyHacks/FlightOperationsBlog/assets/68796232/33cf8d31-7d4a-45e3-9954-f9861ed72c3f)  | ![image](https://github.com/GeekyHacks/FlightOperationsBlog/assets/68796232/5057e04b-fbe3-4423-893b-03e9917de543)l  |

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2024-01-24 23:03 UTC, omar-muhamad commented on app/views/users/_biouser.html.erb
> +      <%= render partial: 'posts/listpost', locals: { post: post } %>
- [ ] As requested by the previous reviewer, As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md#:~:text=page%20to%20another-,Use%20methods%20that%20you%20have%20created%20in%20the%20Blog%20App%20%2D%20processing%20data%20in%20models.,-Hint%3A%20In), Please use the `most_recent_posts` you created before in the user model here to render the 3 most recent posts only on the page, not as you did here.

```suggestion
<% @user.most_recent_posts.each do |post| %>
      <%= render partial: 'posts/listpost', locals: { post: post } %>
```

2024-01-24 23:03 UTC, omar-muhamad commented on app/views/users/show.html.erb
> +</a>
- [ ] As required by the previous reviewer, As per the `users#show` view [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_user_page.png), Please add `see all posts` button here instead of the `back` button you added.

2024-01-24 23:03 UTC, omar-muhamad commented on app/views/posts/index.html.erb
> +          <p><%= comment.user.name %>: <%= comment.text %></p>
- [ ] [Optional] [Highly recommended] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md#:~:text=page%20to%20another-,Use%20methods%20that%20you%20have%20created%20in%20the%20Blog%20App%20%2D%20processing%20data%20in%20models.,-Hint%3A%20In), Please use the `most_recent_comments` method you created in the post model here to render only the 5 most recent comments on the page.

```suggestion
        <% post.most_recent_comments.each do |comment| %>
          <p><%= comment.user.name %>: <%= comment.text %></p>
```
### ⚠️I marked this as optional because the last reviewer forgot to mention it so please consider doing it⚠️

2024-01-25 19:34 UTC, fobadara approved these changes
Hi @GeekyHacks, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![APPRVED](https://user-images.githubusercontent.com/62938735/260206857-3c93f52c-5b21-4f6f-8bc4-be158a13d3cd.gif)
## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-25 20:49 UTC, merged